# In-Class Programming Activity, Day 5

## Spencer Nelson

## Task 1
```{r}
install.packages("mosaicData",repos="http://cran.rstudio.com/")
library(mosaicData)
data(Galton, package = "mosaicData")
nbins <- 10
```
## Task 2
```{r}
min <- min(Galton$height)
max <- max(Galton$height)
evenly_spaced <- seq(min, max, (max-min)/(nbins))
```

## Task 3
```{r}
bin_counts <- table(cut(Galton$height, evenly_spaced))
```

## Task 4
```{r}
xL<- evenly_spaced[-length(evenly_spaced)]
xR<- evenly_spaced[10-length(evenly_spaced)]
count<- as.numeric(bin_counts)
hist_basics<-data.frame(xL,xR,count)
```

## Task 5
```{r}
make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}
# ================
one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}
My_bars <- one_to_five(hist_data = hist_basics)
My_bars<- data.frame(My_bars)
```

```{r}
plot(My_bars, type = "n", main = "Histogram", ylab = "Frequency", xlab = "Height in Inches")
lines(My_bars)
polygon(My_bars, col = "violetred2")
```
## Test statements

```{r}
scoreActivity::score253(5)
```