# In-Class Programming Activity, Day 6

## Spencer Nelson
## Task 1 - Creating a histogram function
```{r}
library(mosaicData)
data(Galton, package = "mosaicData")
nbins <- 10
min <- min(Galton$height)
max <- max(Galton$height)
evenly_spaced <- seq(min, max, (max-min)/(nbins))
bin_counts <- table(cut(Galton$height, evenly_spaced))
xL<- evenly_spaced[-length(evenly_spaced)]
xR<- evenly_spaced[10-length(evenly_spaced)]
count<- as.numeric(bin_counts)
hist_basics<-data.frame(xL,xR,count)
make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}
# ================
one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}
myHistogram<- function(point,hist_data,fill){
  nbins <- 10
min <- min(Galton$height)
max <- max(Galton$height)
evenly_spaced <- seq(min, max, (max-min)/(nbins))
bin_counts <- table(cut(Galton$height, evenly_spaced))
xL<- evenly_spaced[-length(evenly_spaced)]
xR<- evenly_spaced[10-length(evenly_spaced)]
count<- as.numeric(bin_counts)
hist_basics<-data.frame(xL,xR,count)
My_bars <- one_to_five(hist_data = hist_basics)
My_bars<- data.frame(My_bars)
plot(My_bars, type = "n", main = "Histogram", ylab = "Frequency", xlab = "Height in Inches")
lines(My_bars)
polygon(My_bars, col = fill)
}
myHistogram(point,hist_data = hist_basics,"tomato")
```



## Task 2
```{r}

v<-rnorm(10,mean=100,sd=1)
bw<- diff(range(v))/sqrt(length(v))
xlim<- c(min(v)-(3*bw), max(v)+3*bw)
x<- seq(min(xlim), max(xlim), length = 200)
kernel<- function(x,y){
  dnorm(y, mean = x, sd = bw)
}
Dvals<- outer(v,x,FUN=kernel)
density<- colSums(Dvals)/length(v)
dataframe<-data.frame(x,density)
plot(dataframe)

```
##Task 3
```{r}
plotdensity<-function(v, xlim = NULL){
  bw<- diff(range(v))/sqrt(length(v))
x<- seq(min(xlim), max(xlim), length = 200)
kernel<- function(x,y){
  dnorm(y, mean = x, sd = bw)
}
Dvals<- outer(v,x,FUN=kernel)
density<- colSums(Dvals)/length(v)
dataframe<-data.frame(x,density)
plot(dataframe)
invisible()
}
```

## Test statements

```{r}
scoreActivity::score253(6)
```