# In-Class Programming Activity, Day 9

## Spencer Nelson
##Task 1
```{r}

poker_deck<- c(outer(10*2:14,1:4,'+'))
suits<- function(hand){
  hand%%10
}
ranks<- function(hand){
    hand%/%10
}
```
```{r}

is_flush<- function(five_cards){
  length(table(suits(five_cards))) == 1
}
is_straight<- function(five_cards){
  length(table(ranks(five_cards))) == 5
}
is_pair<-function(five_cards){
  max(table(suits(five_cards))) == 2
}
is_two_pair<- function(five_cards){
  max(table(suits(five_cards))) == 2 && max(table(suits(five_cards))) == 2
}
is_straight_flush<- function(five_cards){
  suit_count<- table(suits(five_cards))
  consecutive<-diff(sort(ranks(five_cards)))
  max(suit_count) == 5 && max(consecutive) == 1
}
is_royal_flush<- function(five_cards){
  is_straight_flush(five_cards) && min(table(ranks(five_cards))) == 10  
}
is_full_house<-function(five_cards){
  counts<- table(ranks(five_cards))
  min(counts)==2 && max(counts) == 3
}
is_three_of_a_kind<-function(five_cards){
  suit_count<-table(suits(five_cards))
  max(suit_count)==3
  
}
is_four_of_a_kind<- function(five_cards){
  rank_count<- table(ranks(five_cards))
  max(rank_count)==4
}
test_hand_1<- c(21,24,64,34,102) 
test_hand_2<- c(42,61,34,121,133)
```
##Estimating probabilities
```{r}
before_draw<- function(){
  five_cards<- sample(poker_deck,5)
  if(is_royal_flush(five_cards)){
    return("Royal Flush")
  } 
  if(is_straight_flush(five_cards)){
    return("Straight Flush")
  }
  if(is_four_of_a_kind(five_cards)){
    return("Four of a kind")
  }
  if(is_full_house(five_cards)){
    return("Full House")
  }
  if(is_flush(five_cards)){
    return("Flush")
  }
  if(is_straight(five_cards)){
    return("Straight")
  }
  if(is_three_of_a_kind(five_cards)){
    return("Three of a kind")
  }
  if(is_two_pair(five_cards)){
    return("Two pair")
  }
  if(is_pair(five_cards)){
    return("Pair")
  }
  else{
    return("Bad hand!")
  }
}
```


## Test statements

```{r}
scoreActivity::score253(9)
```