# In-Class Programming Activity, Day 10

##Spencer Nelson
##The logsitic function
```{r}
logistic<- function(x){
  exp(x)/(1+exp(x))
}
```
##Linear Combinations
```{r}
linear_combine<-function(data, coefs){
  result<-0
  for(nm in names(coefs)){
    if(nm=="intercept"){
      result<- result + coefs [[nm]]
    } else {
      if (! nm %in% names(data)) stop("not a variable name")
      result<-result + coefs[[nm]] * data[[nm]]
    }
    
  }
  return(result)
}
```
##Probabilites
```{r}
LL_logistic<-function(data,coefs,outcome){
  result = linear_combine(data,coefs)
  pi<-logistic(result)
  likelihood<-ifelse(outcome, pi, 1-pi)
  sum(log(likelihood))
}
library("ISLR", lib.loc="~/R/library")
attach(Default)
LL_logistic(data=Default, 
            coefs = c(intercept = 1, income = -0.0001), 
            outcome = Default$default == "Yes")
```
##Optimize
```{r}
best_coefs<-optim(c(intercept=1,income=-.0001), 
                  LL_logistic, 
                  outcome=Default$default == "Yes",
                  data=Default,
                  control = list(fnscale=-1))
best_coefs
glm(default == "Yes" ~ income, data=Default, family = binomial)
```
## Test statements

```{r}
scoreActivity::score253(10)
```