# In-Class Programming Activity, Day 13
##Spencer Nelson

##A function framework
```{r}
k_fold1<- function(formula,method=lm,data=mtcars,predfun=predict, k=10){
  mspe <- numeric(k)
  sets<- sample((1:nrow(mtcars) %% k) + 1)
  for (i in 1:k) {
    For_Testing<-mtcars[sets == i, ]
    For_Training<-mtcars[sets!=i, ]
    mod<-lm(mpg~hp+wt+am, data=For_Training)
    pred_vals<-predict(mod,newdata=For_Testing)
    mspe[i] <- mean((For_Testing[["mpg"]]-pred_vals)^2)
  }
  error_estimate<-mean(mspe)
  return(error_estimate)
}
k_fold<- function(formula,method,data,predfun,k){
  mspe <- numeric(k)
  sets<- sample((1:nrow(data) %% k) + 1)
  for (i in 1:k) {
    For_Testing<-data[sets == i, ]
    For_Training<-data[sets!=i, ]
    mod<-method(formula,data=For_Training)
    pred_vals<-predfun(mod,newdata=For_Testing)
    mspe[i] <-mean((For_Testing[[as.character(formula[[2]])]]-pred_vals)^2)
    }
  error_estimate<-mean(mspe)
  return(error_estimate)
}

```

## Test statements

```{r}
scoreActivity::score253(13)
```